### ISSUE TITLE
Add support for a static light list

### ISSUE THREAD

**Issue by 64-bit** [n0remac/Pyweek#10]

**Comment by n0remac** [comment]
I think I started on something like this. 
`
        self.light_list = []
        radius_by_type = {"torch": 70.0, "candle": 40.0}

        for light in self.game_resources.light_list:
            radius = radius_by_type.get(light.properties["type"])
            self.light_list.append(
                self.scene_renderer.light_renderer.create_point_light(
                    (light.center_x, light.center_y),  # Position
                    (
                        1.75,
                        2.75,
                        1.75,
                    ),  # Color, 0 = black, 1 = white, 0.5 = grey, order is RGB This can go over 1.0 because of HDR
                    radius,
                )  # Radius
            )`
